name: hg_cad
channels:
  - pytorch
  - pyg
  - dglteam
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - absl-py=1.3.0
  - aiohttp=3.8.1
  - aiosignal=1.3.1
  - async-timeout=4.0.2
  - attrs=22.1.0
  - blas=1.0
  - blinker=1.5
  - bottleneck=1.3.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - ca-certificates=2022.10.11
  - cachetools=5.2.0
  - certifi=2022.9.24
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.1.3
  - colorama=0.4.5
  - cryptography=38.0.1
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - dgl-cuda11.3=0.9.1
  - fftw=3.3.9
  - fonttools=4.25.0
  - freetype=2.12.1
  - frozenlist=1.2.0
  - fsspec=2022.11.0
  - google-auth=2.14.1
  - google-auth-oauthlib=0.4.6
  - grpcio=1.42.0
  - icc_rt=2022.1.0
  - icu=68.2
  - idna=3.4
  - importlib-metadata=5.0.0
  - intel-openmp=2021.4.0
  - jinja2=3.1.2
  - joblib=1.1.1
  - jpeg=9e
  - kiwisolver=1.4.4
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=11.1.0
  - libdeflate=1.8
  - libpng=1.6.37
  - libprotobuf=3.20.1
  - libtiff=4.4.0
  - libuv=1.40.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.3
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=6.0.2
  - munkres=1.1.4
  - networkx=2.8.4
  - numexpr=2.8.1
  - numpy=1.23.4
  - numpy-base=1.23.4
  - oauthlib=3.2.2
  - openssl=1.1.1s
  - packaging=21.3
  - pandas=1.4.2
  - pillow=9.2.0
  - pip=22.2.2
  - protobuf=3.20.1
  - psutil=5.9.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pydeprecate=0.3.2
  - pyg=2.1.0
  - pyjwt=2.6.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.12.3
  - pysocks=1.7.1
  - python=3.8.5
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytorch=1.12.0
  - pytorch-cluster=1.6.0
  - pytorch-lightning=1.7.7
  - pytorch-mutex=1.0
  - pytorch-scatter=2.0.9
  - pytorch-sparse=0.6.15
  - pytz=2022.1
  - pyu2f=0.1.5
  - pyyaml=6.0
  - qt=5.12.9
  - requests=2.28.1
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - scikit-learn=1.1.3
  - scipy=1.9.3
  - seaborn=0.11.2
  - setuptools=65.5.0
  - six=1.16.0
  - sqlite=3.40.0
  - tensorboard=2.11.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - torchaudio=0.12.0
  - torchmetrics=0.10.3
  - torchvision=0.13.0
  - tornado=6.2
  - tqdm=4.64.1
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - urllib3=1.26.12
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - werkzeug=2.2.2
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.7.2
  - zipp=3.10.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
